#!/usr/bin/env bash

alias ..="cd ..";
alias ...="cd ../..";
alias ....="cd ../../..";
alias ll="ls -la"
alias l="ls -Glah"

alias dt="cd ~/Desktop"
alias db="cd ~/Dropbox"
alias gd="cd Google\ Drive/"

alias gs="git status -s"
alias ga="git add"
alias gaa="git add ."
alias gcm="git commit -m"
alias gpo="git push origin"

alias dc-env="eval $(cachalot env)"
alias dc="docker-compose"
alias dc-loc="docker-compose exec --user drupal drupal bash"

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"

# Ring the terminal bell, and put a badge on Terminal.app’s Dock icon
# (useful when executing time-consuming commands)
alias badge="tput bel"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
