# you installed by curl
# curl -sS https://starship.rs/install.sh | sh

add_newline = true

format = '''
$directory$fill$git_status$git_branch
$character'''

[fill]
symbol = ' '

[character] 
success_symbol = '[\$](green)' 
error_symbol = '[\$](red)' 

[directory]
truncation_length = 0
truncate_to_repo = false
style = 'bright-black'

[git_branch]
style = 'bright-black'
format = '[$branch(:$remote_branch)]($style)'

# get help here https://www.nerdfonts.com/cheat-sheet

[git_status]
disabled = true
format = '[[$all_status$ahead_behind](fg:7 bg:8)](fg:8) '
modified = '~'
ahead = '${count}'
diverged = '±${ahead_count} ${behind_count}'
behind = '${count} '

[package]
disabled = true

